name: Build

on:
    push:
      branches:
        - develop
    workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: install dependencies
        run: npm install

      - name: postinstall
        run: npm run postinstall

      - name: build
        run: npm run build

      - name: build electron win
        run: npm run build:win
