name: Release

on:
    push:
      branches:
        - master
    workflow_dispatch:

jobs:
  release:
    runs-on: windows-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@master
        with:
          node-version: 16

      - name: install dependencies
        run: npm install

      - name: postinstall
        run: npm run postinstall

      - name: build
        run: npm run build

      - name: release electron win
        run: npm run release:win
